function sdm_txt_array = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GPPISS02RUN1VM01S1R1SCCTBL3DMCTSLTRTHPGLMF2C256TRILIN3X1 =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a string array.
%
%  GPPISS02RUN1VM01S1R1SCCTBL3DMCTSLTRTHPGLMF2C256TRILIN3X1 =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  gPPISS02run1VM01S1R1SCCTBL3DMCTSLTRTHPGLMF2c256trilin3x1 = importfile("C:\Users\User\Documents\MRHI\Fix\gPPI_sdm\VM_SA_gPPI\gPPI_SS02_run1_VM-01-S1R1_SCCTBL_3DMCTS_LTR_THPGLMF2c_256_trilin_3x1.0_MNI_SD3DVSS6.00mm_L_Ins.sdm", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 22-Jan-2023 10:04:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["FileVersion", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36"];
opts.SelectedVariableNames = ["FileVersion", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["FileVersion", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["FileVersion", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36"], "EmptyFieldRule", "auto");

% Import the data
sdm_txt_array = readmatrix(filename, opts);

end